# Generated by Django 5.2.6 on 2025-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soldier_id', models.CharField(max_length=20, unique=True)),
                ('rank', models.CharField(choices=[('recruit', 'Recruit'), ('private', 'Private'), ('corporal', 'Corporal'), ('sergeant', 'Sergeant'), ('staff_sergeant', 'Staff Sergeant'), ('officer', 'Officer')], default='recruit', max_length=20)),
                ('unit', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
