# Generated by Django 5.2.6 on 2025-10-18 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='assigned_trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_soldiers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='soldier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soldier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
