# Generated by Django 5.2.6 on 2025-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pushups', models.IntegerField(help_text='Number of pushups in 2 minutes')),
                ('running_distance', models.FloatField(help_text='Distance in kilometers')),
                ('running_time', models.FloatField(help_text='Time in minutes')),
                ('bmi', models.FloatField(help_text='Body Mass Index')),
                ('shooting_accuracy', models.FloatField(help_text='Percentage accuracy')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'soldier'],
            },
        ),
    ]
