# Generated by Django 5.2.6 on 2025-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('military_tactics', 'Military Tactics'), ('weapon_training', 'Weapon Training'), ('communication', 'Communication'), ('leadership', 'Leadership'), ('first_aid', 'First Aid'), ('physical_training', 'Physical Training'), ('general_knowledge', 'General Knowledge')], max_length=50)),
                ('marks', models.FloatField()),
                ('total_marks', models.FloatField(default=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'soldier'],
            },
        ),
    ]
