# Generated by Django 5.2.6 on 2025-11-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='percentage',
            field=models.FloatField(default=56, editable=False),
            preserve_default=False,
        ),
    ]
